[package]
name = "cw4626"
version = "0.1.0"
authors = ["chinhnotional <eyescryptoinsights@gmail.com>"]
edition = "2018"
description = "Definition and types for the CosmWasm-4626 interface"
license = "Apache-2.0"
repository = "https://github.com/CosmWasm/cw-plus"
homepage = "https://cosmwasm.com"
documentation = "https://docs.cosmwasm.com"

[dependencies]
cw-utils = { path = "../../packages/utils", version = "0.13.4" }
cosmwasm-std = { version = "1.0.0" }
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }

[dev-dependencies]
cosmwasm-schema = { version = "1.0.0" }
